# Generated by Django 5.1.2 on 2024-10-10 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.department'),
        ),
    ]
