# Generated by Django 5.1.2 on 2024-10-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0002_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
