# Generated by Django 5.1.2 on 2024-10-11 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0004_alter_employee_department_alter_employee_fio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Свясь с сотрудником - директором департамента'),
        ),
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='structure.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fio',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='post',
            field=models.CharField(max_length=64, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.IntegerField(verbose_name='Зарплата'),
        ),
    ]
