# Generated by Django 5.1.2 on 2024-10-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0005_alter_department_email_alter_department_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Связь с сотрудником - директором департамента'),
        ),
    ]
