# Generated by Django 5.1.2 on 2024-10-11 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0006_alter_department_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Департамент', 'verbose_name_plural': 'Департаменты'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
