# Generated by Django 5.1.2 on 2024-10-25 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0007_alter_department_options_alter_employee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='structure.department', verbose_name='Департамент'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='photos/default_photo.jpg', upload_to='photos/', verbose_name='Фото'),
        ),
    ]
